public with sharing class forcec {
   public forcec(){

   }

        // public PageReference task2a(){
        //     return Page.;
        // }

        public PageReference task3exc(){
            return Page.task3ex;
        }
        public PageReference task21(){
            return Page.task22;
        }

        public PageReference task3(){
            return Page.task3c;
        }
        public PageReference task3newc(){
            return Page.task3new;
        }
        // public PageReference task4(){
        //     return Page.task4;
        // }
        public PageReference task5finalc(){
            return Page.taskfinal;
        }

        public PageReference taskregc(){
            return Page.taskregp;
        }
        public PageReference taskloginc(){
            return Page.taskloginp;
        }
        


        
        


    
}
