public  class taskregc {
    // public taskregc() {

    // }
    public taskregc(ApexPages.StandardController Controller) {
    
    }
    // public PageReference goToPageTwo(){
    //     System.debug('datt1');
    //     Pagereference p = new PageReference('./https://mvclouds65-dev-ed--c.develop.vf.force.com/apex/taskloginp');
    //     p.setRedirect(true);
    //     System.debug('datt');
    //     return p;
    // }

    // public PageReference printView(){
    //     PageReference oPageRef=Page.taskloginp;
    //     
    //     oPageRef.setRedirect(false);

    //     return oPageRef;
    // }
  
}

